---
- name: clone profile config
  become: true
  become_user: "{{ main_user }}"
  git:
    repo: https://github.com/mtnstar/profile.git
    dest: "~/git/setup/profile/"
    update: yes
    version: master

- name: create config dir symlink
  become: true
  become_user: "{{ main_user }}"
  file: path=~/.config/hypr
        src=~/git/setup/profile/hypr
        state=link
        force=yes

- name: ensure local applications dir exists
  become: true
  become_user: "{{ main_user }}"
  file:
    path: ~/.local/share/applications
    state: directory

- name: add restart waybar launcher entry
  become: true
  become_user: "{{ main_user }}"
  template:
    src: restart-waybar.desktop
    dest: ~/.local/share/applications/restart-waybar.desktop
    mode: 0644
