---
- name: Configure desktop
  hosts: localhost

  roles:
    #- { role: base, tags: ['base'] }
    - { role: profile, tags: ['profile'] }
    - { role: git, tags: ['git'] }
    - { role: omarchy, tags: ['omarchy'] }
    - { role: nitrokey, tags: ['nitrokey'] }
    - { role: yubikey, tags: ['yubikey'] }
    - { role: podman, tags: ['podman'] }
    - { role: nextcloud, tags: ['nextcloud'] }
    - { role: firefox, tags: ['firefox'] }
    - { role: nvim, tags: ['nvim'] }
    - { role: hyprland, tags: ['hyprland'] }
    - { role: yay, tags: ['yay'] }
    - { role: snap, tags: ['snap'] }
    - { role: x1n, tags: ['x1n'] }
    - { role: video, tags: ['video'] }
    - { role: utils, tags: ['utils'] }
    - { role: wireguard, tags: ['wireguard'] }
    - { role: slack, tags: ['slack'] }
    - { role: udev, tags: ['udev'] }
    - { role: printer, tags: ['printer'] }
    - { role: wine, tags: ['wine'] }
    - { role: asdf, tags: ['asdf'] }
    - { role: dev-tools, tags: ['dev-tools'] }
    - { role: x1c, tags: ['x1c'] }
    #- { role: utils, tags: ['utils'] }
    #- { role: network-tools, tags: ['network-tools'] }
    #- { role: terminal, tags: ['terminal'] }
    #- { role: chromium, tags: ['chromium'] }
    #- { role: vim, tags: ['vim'] }
    #- { role: ruby, tags: ['ruby'] }
    #- { role: docker, tags: ['docker'] }
    #- { role: msg-tools, tags: ['msg-tools'] }
    #- { role: hyprland, tags: ['hyprland'] }
    #- { role: android, tags: ['android'] }
    #- { role: office, tags: ['office'] }
    #- { role: gfx, tags: ['gfx'] }
    #- { role: kvm, tags: ['kvm'] }
    #- { role: nix, tags: ['nix'] }
    #- { role: astro, tags: ['astro'] }
