---
- name: clone omarchy star blue theme
  become: true
  become_user: "{{ main_user }}"
  git: repo=https://github.com/mtnstar/omarchy-star-blue-theme.git dest=~/.config/omarchy/themes/star-blue update=yes

- name: install kitty
  pacman:
    name:
      - kitty

- name: 
  copy:
    dest: ~/.config/xdg-terminals.list
    content: |
      kitty.desktop

  become: true
  become_user: "{{ main_user }}"
