---
- name: Install dde requirements
  community.general.pacman:
    name: mkcert
    state: present

- name: Add DDE repository to pacman.conf
  blockinfile:
    path: /etc/pacman.conf
    marker: "# {mark} ANSIBLE MANAGED - DDE REPO"
    block: |
      [dde]
      Server = https://packages.dde.sh/arch/$arch
      SigLevel = Required DatabaseOptional

- name: Import DDE signing key
  ansible.builtin.shell:
    cmd: curl -fsSL https://packages.dde.sh/arch/key.gpg | pacman-key --add -
  changed_when: true

- name: Get DDE key fingerprint
  ansible.builtin.shell:
    cmd: >
      curl -fsSL https://packages.dde.sh/arch/key.gpg |
      gpg --with-colons --import-options show-only --import 2>/dev/null |
      awk -F: '/^fpr/{print $10; exit}'
  register: dde_key_fingerprint
  changed_when: false

- name: Locally sign DDE key
  ansible.builtin.command:
    cmd: "pacman-key --lsign-key {{ dde_key_fingerprint.stdout }}"
  changed_when: true

- name: Install dde package
  community.general.pacman:
    name: dde
    state: present
    update_cache: true
