---
- name: Install claude-code
  pacman:
    name:
      - claude-code
    state: present

- name: Install Claude Desktop
  become: yes
  become_user: aur_builder
  kewlfft.aur.aur:
    name: claude-desktop-bin
    state: present
