---
- name: Install 5g modem stuff
  include_tasks: "5g_modem.yml"
  when: "'ThinkPad X1 Carbon Gen 12' in ansible_facts['product_version']"

- name: Ensure gfx drivers
  include_tasks: "gfx.yml"
  when: "'ThinkPad X1 Carbon Gen 12' in ansible_facts['product_version']"
