---
- name: Install image tools
  pacman:
    name:
      - imagemagick
      - perl-image-exiftool
    state: present

- name: Create a symlink for exiftool
  file:
    src: /usr/bin/vendor_perl/exiftool
    dest: /usr/bin/exiftool
    state: link

- name: Install beekeeper-studio-bin
  kewlfft.aur.aur:
    name:
      - beekeeper-studio-bin
    state: present
  become: true
  become_user: aur_builder
