---
- name: Install image tools
  pacman:
    name:
      - imagemagick
      - perl-image-exiftool
    state: present

- name: Create a symlink for exiftool
  file:
    src: /usr/bin/vendor_perl/exiftool
    dest: /usr/bin/exiftool
    state: link
