---
- name: clone vim config
  become: true
  become_user: "{{ main_user }}"
  git:
    repo: https://github.com/mtnstar/nvim.git
    dest: "~/git/setup/nvim"
    update: yes
    version: main

- name: Check if config dir path is a symlink
  ansible.builtin.stat:
    path: ~/.config/nvim
  register: nvim_config_dir_stat

- name: Remove config directory if it is not a symlink
  ansible.builtin.file:
    path: ~/.config/nvim
    state: absent
  when:
    - nvim_config_dir_stat.stat.exists
    - not nvim_config_dir_stat.stat.islnk

- name: create config dir symlink
  become: true
  become_user: "{{ main_user }}"
  file: path=~/.config/nvim
        src=~/git/setup/nvim
        state=link
        force=yes
